name: Deploy to Vercel

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - "frontend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build and Deploy Backend
        if: contains(github.event.head_commit.modified, 'backend/')
        run: |
          cd backend
          vercel --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build and Deploy Frontend
        if: contains(github.event.head_commit.modified, 'frontend/')
        run: |
          cd frontend
          vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
